setenv AXI4LITE_PROJECT `pwd` 

setenv AXI4LITE_MASTER "$AXI4LITE_PROJECT/src/axi4LiteMasterVIP/" 
setenv AXI4LITE_SLAVE "$AXI4LITE_PROJECT/src/axi4LiteSlaveVIP/" 

setenv AXI4LITE_MASTERWRITE "$AXI4LITE_MASTER/src/axi4LiteMasterWriteVIP"
setenv AXI4LITE_MASTERREAD "$AXI4LITE_MASTER/src/axi4LiteMasterReadVIP"

setenv AXI4LITE_SLAVEWRITE "$AXI4LITE_SLAVE/src/axi4LiteSlaveWriteVIP"
setenv AXI4LITE_SLAVEREAD "$AXI4LITE_SLAVE/src/axi4LiteSlaveReadVIP"
