+incdir+../../src/
+incdir+../../src/axi4LiteReadMasterVIP/masterReadAgent/
+incdir+../../src/axi4LiteReadMasterVIP/masterReadAgent/masterReadSequences/
+incdir+../../src/axi4LiteReadMasterVIP/masterReadAgentBFM/
+incdir+../../src/axi4LiteReadMasterVIP/
+incdir+../../src/tb/test/

../../src/Axi4LiteReadMasterGlobalPkg.sv
../../src/axi4LiteReadMasterVIP/masterReadAgent/Axi4LiteMasterReadPkg.sv
../../src/axi4LiteReadMasterVIP/masterReadAgent/masterReadSequences/Axi4LiteMasterReadSeqPkg.sv
../../src/axi4LiteReadMasterVIP/Axi4LiteReadMasterEnvPkg.sv
../../src/tb/test/Axi4LiteReadMasterTestPkg.sv
../../src/axi4LiteReadMasterVIP/masterReadAgentBFM/Axi4LiteMasterReadInterface.sv
../../src/axi4LiteReadMasterVIP/masterReadAgentBFM/Axi4LiteMasterReadAssertions.sv
../../src/axi4LiteReadMasterVIP/masterReadAgentBFM/Axi4LiteMasterReadCoverProperty.sv
../../src/axi4LiteReadMasterVIP/masterReadAgentBFM/Axi4LiteMasterReadDriverBFM.sv
../../src/axi4LiteReadMasterVIP/masterReadAgentBFM/Axi4LiteMasterReadMonitorBFM.sv
../../src/axi4LiteReadMasterVIP/masterReadAgentBFM/Axi4LiteMasterReadAgentBFM.sv
../../src/tb/axi4LiteMasterReadHdlTop.sv
../../src/tb/axi4LiteMasterReadHvlTop.sv
